=== ricks03/TotalHost/database/_UserStatus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_UserStatus" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_UserStatus">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACD801ftE+zTpQQsePzSldkAAAAAEB7foe8rONAAACOAAEERH5VAHMA
ZQByAF8AUwB0AGEAdAB1AHMAAAAAAAAA4xxwAfr2s0KbdUazsAFFywcAAACD801f
tE+zTpQQsePzSldkVQBzAGUAcgBfAFMAdABhAHQAdQBzAF8AVgBhAGwAdQBlAAAA
AAAAAJxvI0uvlnFEvfjZRRqfWJ0HAAAAg/NNX7RPs06UELHj80pXZFUAcwBlAHIA
XwBTAHQAYQB0AHUAcwAAAAAAAABFkQ77+o13T7+6u/1vI00yBwAAAIPzTV+0T7NO
lBCx4/NKV2RVAHMAZQByAF8AUwB0AGEAdAB1AHMAXwB0AHgAdAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAADAAAAAMAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="User_Status" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="User_Status_txt" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Current Account Status"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="User_Status_Detail" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="6855"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== ricks03/TotalHost/database.odbc/_UserStatus.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="_UserStatus.xsd" generated="2021-05-14T12:51:27">
<_UserStatus>
<User_Status>1</User_Status>
<User_Status_txt>Active</User_Status_txt>
<User_Status_Detail>Account active and in good standing</User_Status_Detail>
</_UserStatus>
<_UserStatus>
<User_Status>-1</User_Status>
<User_Status_txt>Locked</User_Status_txt>
<User_Status_Detail>Account Locked for multiple failed logins</User_Status_Detail>
</_UserStatus>
<_UserStatus>
<User_Status>-2</User_Status>
<User_Status_txt>Suspended</User_Status_txt>
<User_Status_Detail>Inactivated temporarily for some reason</User_Status_Detail>
</_UserStatus>
<_UserStatus>
<User_Status>-3</User_Status>
<User_Status_txt>Inactive</User_Status_txt>
<User_Status_Detail>Account not accessed for x days</User_Status_Detail>
</_UserStatus>
<_UserStatus>
<User_Status>-4</User_Status>
<User_Status_txt>Disabled</User_Status_txt>
<User_Status_Detail>Account no longer valid</User_Status_Detail>
</_UserStatus>
<_UserStatus>
<User_Status>-5</User_Status>
<User_Status_txt>New</User_Status_txt>
<User_Status_Detail>New Inactive User Account</User_Status_Detail>
</_UserStatus>
<_UserStatus>
<User_Status>2</User_Status>
<User_Status_txt>Reset</User_Status_txt>
<User_Status_Detail>Password Reset</User_Status_Detail>
</_UserStatus>
<_UserStatus>
<User_Status>-6</User_Status>
<User_Status_txt>Banned</User_Status_txt>
<User_Status_Detail>User Has Been Banned</User_Status_Detail>
</_UserStatus>
<_UserStatus>
<User_Status>-7</User_Status>
<User_Status_txt>Pending</User_Status_txt>
<User_Status_Detail>User Account Pending</User_Status_Detail>
</_UserStatus>
</dataroot>
